name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Android Release
        run: |
          cd android
          chmod +x gradlew
          # Limpeza profunda de caches e autolinking viciado
          ./gradlew clean
          rm -rf .cxx
          rm -rf app/build/generated/autolinking
          # Build forçando a desativação da New Arch
          ./gradlew assembleRelease -x lint -PnewArchEnabled=false
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FollowApp-APK
          path: android/app/build/outputs/apk/release/app-release.apk
