# CONFIGURAÇÕES DE MEMÓRIA
org.gradle.jvmargs=-Xmx4048m -XX:MaxMetaspaceSize=1024m

# SUPORTE ANDROIDX
android.useAndroidX=true
android.enableJetifier=true

# NOVA ARQUITETURA (OBRIGATÓRIO PARA RN 0.85)
newArchEnabled=true
hermesEnabled=true

# OTIMIZAÇÃO DE ARQUITETURAS (AGILIZA O BUILD)
reactNative.Architectures=arm64-v8a,x86_64

# --- FIX PARA AUTOLINKING E EMPTY OUTPUT ---
# Informa ao Gradle onde está a raiz do projeto (node_modules)
PROJECT_ROOT=..
# Garante que o Gradle use o comando 'node' do sistema
reactNative.nodeExecutableAndArgs=node

# SILENCIAR AVISOS DO FIREBASE
RNFB_SUPPRESS_NEW_ARCHITECTURE_WARNING=true

# CONFIGURAÇÕES DE VELOCIDADE
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true
org.gradle.parallel=false
org.gradle.configureondemand=true
